service: layer-pandas

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer: 
      name: python-pandas
      description: "Layer which contains pandas library"
      compatibleRuntimes:
        - python3.8
