service: demo-lambdas

frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  runtime: python3.8

functions:
  pandas_version:
    handler: handler.pandas_version
    layers:
      - arn:aws:lambda:us-east-1:{aws_account_number}:layer:python-pandas:1
  numpy_version:
    handler: handler.numpy_version
    layers:
      - arn:aws:lambda:us-east-1:{aws_account_number}:layer:python-numpy:2
